# Generated by Django 5.0.2 on 2024-10-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=100)),
                ('numero_linha', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('processador', models.CharField(max_length=100)),
                ('memoria', models.CharField(max_length=100)),
                ('hd', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('numero_nota_fiscal', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(max_length=100)),
                ('sistema_operacional', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='BIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(blank=True, max_length=100, null=True)),
                ('bitswidth', models.IntegerField(blank=True, null=True)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('publisher_id', models.IntegerField()),
                ('version_id', models.IntegerField()),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='ProntuarioCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('motivo_ocorrencia', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('unidade_destino', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.celular')),
            ],
        ),
        migrations.CreateModel(
            name='ProntuarioComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_ocorrencia', models.CharField(max_length=100)),
                ('numero_chamado', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.computador')),
            ],
        ),
        migrations.CreateModel(
            name='ProntuarioMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('motivo_ocorrencia', models.TextField()),
                ('unidade_destino', models.CharField(max_length=100)),
                ('local_destino', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('publisher_id', models.IntegerField()),
                ('version_id', models.IntegerField()),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('disk_size', models.IntegerField()),
                ('firmware', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware')),
            ],
        ),
    ]
