# Generated by Django 5.0.2 on 2024-10-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_accountinfo_architecture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipoitem'),
        ),
    ]
