# Generated by Django 5.0.2 on 2024-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_tipoitem_alter_estoque_tipo_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
