# Generated by Django 5.0.2 on 2024-10-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.status'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoitem'),
        ),
    ]
