# Generated by Django 5.0.2 on 2024-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_estoque_status_alter_estoque_tipo_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controlekit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('data_entrega', models.DateField()),
                ('modelo', models.CharField(max_length=100)),
                ('estabelecimento', models.CharField(max_length=100)),
                ('centro_custo', models.CharField(max_length=100)),
                ('data_final', models.DateField()),
            ],
        ),
    ]
