# Generated by Django 5.0.2 on 2024-10-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_controlekit'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlekit',
            name='matricula',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlekit',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
