# Generated by Django 5.0.2 on 2024-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_controlekit_matricula_controlekit_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('data_entrega', models.DateField()),
                ('modelo', models.CharField(max_length=100)),
                ('estabelecimento', models.CharField(max_length=100)),
                ('centro_custo', models.CharField(max_length=100)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('data_final', models.DateField()),
            ],
        ),
    ]
