# Generated by Django 5.0.2 on 2024-10-25 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_controlefones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.status'),
        ),
    ]
