# Generated by Django 5.0.2 on 2024-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_celular_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='centro_custo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
