# Generated by Django 5.0.2 on 2024-10-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_celular_centro_custo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celular',
            old_name='unidade',
            new_name='estabelecimento',
        ),
    ]
