# Generated by Django 5.0.2 on 2024-10-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_monitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='localizacao',
            field=models.CharField(default='Mesa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuariomonitor',
            name='localizacao_destino',
            field=models.CharField(default='Mesa', max_length=100),
            preserve_default=False,
        ),
    ]
