# Generated by Django 5.0.2 on 2024-10-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_monitor_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='estabelecimento',
            field=models.CharField(default='101', max_length=100),
            preserve_default=False,
        ),
    ]
