# Generated by Django 5.0.2 on 2024-10-28 11:52

import django.core.validators
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_remove_monitor_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='arquivo_celular',
            field=models.FileField(blank=True, null=True, upload_to=inventario.models.upload_to),
        ),
        migrations.AlterField(
            model_name='celular',
            name='imei',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator('^\\d{15}$', 'O IMEI deve conter 15 dígitos numéricos')]),
        ),
        migrations.AlterField(
            model_name='celular',
            name='numero_linha',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator('^\\d{15}$', 'O número da linha deve conter 15 dígitos numéricos')]),
        ),
    ]
