# Generated by Django 5.0.2 on 2024-10-28 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_celular_arquivo_celular_alter_celular_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='numero_linha',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^\\d{11}$', 'O número da linha deve conter 11 dígitos numéricos')]),
        ),
    ]
