# Generated by Django 5.0.2 on 2024-10-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_celular_numero_linha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='departamento',
            new_name='Estabelecimento',
        ),
        migrations.RenameField(
            model_name='computador',
            old_name='unidade',
            new_name='centro_custo',
        ),
    ]
