# Generated by Django 5.0.2 on 2024-10-28 17:48

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_rename_numero_chamado_prontuariocomputador_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='arquivo_computador',
            field=models.FileField(blank=True, null=True, upload_to=inventario.models.upload_to),
        ),
        migrations.AlterField(
            model_name='computador',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.status'),
        ),
    ]
