# Generated by Django 5.0.2 on 2024-10-28 19:04

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_computador_arquivo_computador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='Estabelecimento',
            new_name='estabelecimento',
        ),
        migrations.AlterField(
            model_name='computador',
            name='arquivo_computador',
            field=models.FileField(blank=True, null=True, upload_to=inventario.models.upload_to),
        ),
    ]
