# Generated by Django 5.0.2 on 2024-10-31 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_rename_estabelecimento_computador_estabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware'),
        ),
    ]
