# Generated by Django 5.0.2 on 2024-11-04 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_alter_computador_hardware'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('data_desligamento', models.DateField()),
                ('data_limite', models.DateField()),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('bloqueio_email', models.BooleanField(default=False)),
                ('bloqueio_fluig', models.BooleanField(default=False)),
                ('bloqueio_datasul', models.BooleanField(default=False)),
                ('bloqueio_monday', models.BooleanField(default=False)),
                ('bloqueio_qualiteam', models.BooleanField(default=False)),
                ('bloqueio_portal_chamados', models.BooleanField(default=False)),
                ('bloqueio_usuario_impressora', models.BooleanField(default=False)),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastro_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_alteracao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracao_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
