# Generated by Django 5.0.2 on 2024-11-04 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_usuariodesligamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodesligamento',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
