# Generated by Django 5.0.2 on 2024-11-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_alter_usuariodesligamento_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_datasul',
            field=models.CharField(blank=True, help_text='Usuário Datasul a ser bloqueado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_email',
            field=models.CharField(blank=True, help_text='Usuário de e-mail a ser bloqueado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_fluig',
            field=models.CharField(blank=True, help_text='Usuário Fluig a ser bloqueado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_goglobal',
            field=models.CharField(blank=True, help_text='Usuário Go-Global a ser bloqueado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_impressora',
            field=models.CharField(blank=True, help_text='Usuário de Impressora (Matriz) a ser bloqueado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_monday',
            field=models.CharField(blank=True, help_text='Usuário Monday a ser bloqueado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_portal_chamados',
            field=models.CharField(blank=True, help_text='Usuário do Portal de Chamados a ser bloqueado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='usuario_qualiteam',
            field=models.CharField(blank=True, help_text='Usuário Qualiteam a ser bloqueado', max_length=100, null=True),
        ),
    ]
