# Generated by Django 5.0.2 on 2024-11-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_alter_accountinfo_fields_14_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioDesligamento',
        ),
    ]
