# Generated by Django 5.0.2 on 2025-02-28 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_delete_usuariodesligamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='celular',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celular_alteracao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celular',
            name='usuario_inclusao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='celular_inclusao', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuariocelular',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prontuariocelular',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuariocelular',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuario_alteracao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prontuariocelular',
            name='usuario_inclusao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prontuario_inclusao', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
