# Generated by Django 5.0.2 on 2025-03-03 12:23

import django.core.validators
import django.db.models.deletion
import inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_celular_data_alteracao_celular_data_inclusao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linha', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^\\d{11}$', 'O número da linha deve conter 11 dígitos numéricos')])),
                ('usuario', models.CharField(max_length=100)),
                ('estabelecimento', models.CharField(max_length=100)),
                ('centro_custo', models.CharField(max_length=100)),
                ('arquivo_linha', models.FileField(blank=True, null=True, upload_to=inventario.models.upload_to)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.status')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linha_alteracao', to=settings.AUTH_USER_MODEL)),
                ('usuario_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linha_inclusao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProntuarioLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('motivo_ocorrencia', models.TextField()),
                ('unidade_destino', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.acoesprontuario')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.linha')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuario_linha_alteracao', to=settings.AUTH_USER_MODEL)),
                ('usuario_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuario_linha_inclusao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
