# Generated by Django 5.0.2 on 2025-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_estoquemovimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquemovimentacao',
            name='chamado',
        ),
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='motivo',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Chamado', 'Chamado'), ('Inventário', 'Inventário')], default='Monday', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='nova_contratacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
