# Generated by Django 5.0.2 on 2025-03-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_remove_estoquemovimentacao_chamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='tipo',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Notebook', 'Notebook')], default='Notebook', max_length=20),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventario.estoque'),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='nova_contratacao',
            field=models.CharField(default='Monday', max_length=100),
            preserve_default=False,
        ),
    ]
