# Generated by Django 5.0.2 on 2025-03-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_computador_tipo_alter_estoquemovimentacao_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
