# Generated by Django 5.0.2 on 2025-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_alter_hardware_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='hostname',
            field=models.CharField(max_length=100, unique=True),
        )
    ]
