# Generated by Django 5.0.2 on 2025-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_alter_computador_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='patrimonio',
            field=models.CharField(max_length=100),
        ),
    ]
