# Generated by Django 5.0.2 on 2025-05-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_alter_computador_patrimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='tipo',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Notebook', 'Notebook'), ('Servidor', 'Servidor')], default='Notebook', max_length=20),
        ),
    ]
