# Generated by Django 5.0.2 on 2025-08-19 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0041_alter_computador_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariocomputador',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prontuariocomputador',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuariocomputador',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuario_computador_alteracao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prontuariocomputador',
            name='usuario_inclusao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prontuario_computador_inclusao', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
