# Generated by Django 5.0.2 on 2024-11-07 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('data_desligamento', models.DateField()),
                ('data_limite', models.DateField()),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('bloqueio_email', models.BooleanField(default=False)),
                ('usuario_email', models.CharField(blank=True, help_text='Usuário de e-mail a ser bloqueado', max_length=100, null=True)),
                ('bloqueio_fluig', models.BooleanField(default=False)),
                ('usuario_fluig', models.CharField(blank=True, help_text='Usuário Fluig a ser bloqueado', max_length=100, null=True)),
                ('bloqueio_datasul', models.BooleanField(default=False)),
                ('usuario_datasul', models.CharField(blank=True, help_text='Usuário Datasul a ser bloqueado', max_length=100, null=True)),
                ('usuario_goglobal', models.CharField(blank=True, help_text='Usuário Go-Global a ser bloqueado', max_length=100, null=True)),
                ('bloqueio_monday', models.BooleanField(default=False)),
                ('usuario_monday', models.CharField(blank=True, help_text='Usuário Monday a ser bloqueado', max_length=100, null=True)),
                ('bloqueio_qualiteam', models.BooleanField(default=False)),
                ('usuario_qualiteam', models.CharField(blank=True, help_text='Usuário Qualiteam a ser bloqueado', max_length=100, null=True)),
                ('bloqueio_portal_chamados', models.BooleanField(default=False)),
                ('usuario_portal_chamados', models.CharField(blank=True, help_text='Usuário do Portal de Chamados a ser bloqueado', max_length=100, null=True)),
                ('bloqueio_usuario_impressora', models.BooleanField(default=False)),
                ('usuario_impressora', models.CharField(blank=True, help_text='Usuário de Impressora (Matriz) a ser bloqueado', max_length=100, null=True)),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastro_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_alteracao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracao_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
