# Generated by Django 5.0.2 on 2024-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFluig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Login')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
    ]
