# Generated by Django 5.0.2 on 2024-11-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_process_active'),
        ('suporte', '0002_usuariofluig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('grupos_switch', models.ManyToManyField(to='administration.groupprocess', verbose_name='Grupos para Substituição')),
                ('usuario_a_substituir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_como_substituido', to='suporte.usuariofluig', verbose_name='Usuário a ser Substituído')),
                ('usuario_substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_como_substituto', to='suporte.usuariofluig', verbose_name='Usuário Substituto')),
            ],
        ),
    ]
