# Generated by Django 5.0.2 on 2024-11-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0004_substituicao_usuario_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodesligamento',
            name='envio_email_gestor',
            field=models.BooleanField(default=False, help_text='Indica se um email será enviado ao gestor'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='gestor',
            field=models.CharField(blank=True, help_text='Nome do gestor responsável', max_length=100, null=True),
        ),
    ]
