# Generated by Django 5.0.2 on 2024-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0005_usuariodesligamento_envio_email_gestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodesligamento',
            name='backup_desktop',
            field=models.BooleanField(default=False, help_text='Backup da Área de Trabalho/Documentos realizado'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='backup_email',
            field=models.BooleanField(default=False, help_text='Backup do e-mail realizado'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='backup_onedrive',
            field=models.BooleanField(default=False, help_text='Backup do OneDrive realizado'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='devolucao_celular',
            field=models.BooleanField(default=False, help_text='Celular devolvido'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='devolucao_computador',
            field=models.BooleanField(default=False, help_text='Computador devolvido'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='observacao_celular',
            field=models.TextField(blank=True, help_text='Observações sobre a devolução do celular', null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='observacao_computador',
            field=models.TextField(blank=True, help_text='Observações sobre a devolução do computador', null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='observacao_desktop',
            field=models.TextField(blank=True, help_text='Observações sobre o backup da Área de Trabalho/Documentos', null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='observacao_email',
            field=models.TextField(blank=True, help_text='Observações sobre o backup do e-mail', null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='observacao_onedrive',
            field=models.TextField(blank=True, help_text='Observações sobre o backup do OneDrive', null=True),
        ),
    ]
