# Generated by Django 5.0.2 on 2025-06-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0007_ms365tenant_ms365usersearchlog_ms365userupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioM365',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='E-mail do Usuário')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('business_phones', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_title', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='suporte.ms365tenant')),
            ],
            options={
                'verbose_name': 'Usuário M365',
                'verbose_name_plural': 'Usuários M365',
                'ordering': ['display_name'],
            },
        ),
    ]
