# Generated by Django 5.0.2 on 2025-08-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0008_usuariom365'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariom365',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant', to='suporte.ms365tenant'),
        ),
    ]
