# Generated by Django 5.0.2 on 2025-08-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0009_alter_usuariom365_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodesligamento',
            name='bloqueio_qualiteam',
        ),
        migrations.RemoveField(
            model_name='usuariodesligamento',
            name='usuario_qualiteam',
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='backup_desktop_C',
            field=models.BooleanField(default=False, help_text='Backup do Disco C realizado'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='backup_desktop_documentos',
            field=models.BooleanField(default=False, help_text='Backup da pasta Documentos realizado'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='backup_desktop_download',
            field=models.BooleanField(default=False, help_text='Backup da pasta Downloads realizado'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='backup_keepit',
            field=models.BooleanField(default=False, help_text='Backup do Keepit realizado'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='data_backup_keepit',
            field=models.DateField(blank=True, help_text='Data em que o backup do Keepit foi feito', null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='devolucao_periferico',
            field=models.BooleanField(default=False, help_text='Periféricos devolvidos'),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='observacao_periferico',
            field=models.TextField(blank=True, help_text='Observações sobre a devolução de periféricos', null=True),
        ),
        migrations.AddField(
            model_name='usuariodesligamento',
            name='obsservao_datasul',
            field=models.TextField(blank=True, help_text='Observações sobre o Datasul', null=True),
        ),
    ]
