# Generated by Django 5.0.2 on 2024-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_user_enviar_email_desligados_user_nome_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash_gravatar',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
