# Generated by Django 5.0.2 on 2024-11-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_groupprocess_process_groupprocessselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprocessselection',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.process'),
        ),
    ]
