# Generated by Django 5.0.2 on 2024-11-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_groupprocessselection_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
