# Generated by Django 5.0.2 on 2024-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_process_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanager',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
