# Generated by Django 5.0.2 on 2024-11-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_passwordmanager_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanager',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
