# Generated by Django 5.0.2 on 2024-11-14 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_passwordmanager_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanager',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='passwordmanager',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_alterations', to=settings.AUTH_USER_MODEL),
        ),
    ]
