# Generated by Django 5.0.2 on 2024-11-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_passwordmanager_data_alteracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('modulo', models.CharField(max_length=100, verbose_name='Módulo')),
                ('tipo_dado', models.CharField(choices=[('inteiro', 'Inteiro'), ('booleano', 'Booleano'), ('string', 'String'), ('secret', 'Secret')], max_length=20, verbose_name='Tipo de Dado')),
                ('valor', models.TextField(verbose_name='Valor')),
            ],
        ),
    ]
