# Generated by Django 5.0.2 on 2024-11-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_parametro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordmanager',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='passwordmanager',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='passwordmanager',
            name='usuario_alteracao',
        ),
        migrations.DeleteModel(
            name='PasswordGroup',
        ),
        migrations.DeleteModel(
            name='PasswordType',
        ),
        migrations.DeleteModel(
            name='PasswordManager',
        ),
    ]
