# Generated by Django 5.0.2 on 2024-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=50)),
                ('message_id', models.CharField(max_length=100)),
                ('message_body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('stage', models.CharField(default='inicio', max_length=100)),
            ],
        ),
    ]
