# Generated by Django 5.0.2 on 2024-08-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
