# Generated by Django 5.0.2 on 2024-08-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_tabela'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabela',
            new_name='contatos',
        ),
    ]
