# Generated by Django 5.0.2 on 2024-08-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_rename_tabela_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='cargo',
            field=models.CharField(default='Cargo', max_length=50),
        ),
        migrations.AddField(
            model_name='contatos',
            name='setor',
            field=models.CharField(default='TI', max_length=50),
        ),
    ]
