# Generated by Django 5.0.2 on 2024-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiFuncionariosCombio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(blank=True, db_column='Mes', null=True)),
                ('ano', models.IntegerField(blank=True, db_column='Ano', null=True)),
                ('cdn_funcionario', models.IntegerField(blank=True, null=True)),
                ('cdn_estab', models.CharField(blank=True, max_length=10, null=True)),
                ('cdn_empresa', models.CharField(blank=True, max_length=6, null=True)),
                ('status_funcionario', models.CharField(blank=True, max_length=25, null=True)),
                ('nom_funcionario', models.CharField(blank=True, max_length=100, null=True)),
                ('dat_admis_func', models.DateField(blank=True, null=True)),
                ('dat_desligto_func', models.DateField(blank=True, null=True)),
                ('plano_lotacao', models.IntegerField(blank=True, null=True)),
                ('cod_unid_lotac', models.CharField(blank=True, max_length=40, null=True)),
                ('des_unid_lotac', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_rh_ccusto', models.CharField(blank=True, max_length=40, null=True)),
                ('des_ccusto', models.CharField(blank=True, max_length=80, null=True)),
                ('sindicato', models.IntegerField(blank=True, null=True)),
                ('des_sindicato', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_turno', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_turma', models.CharField(blank=True, max_length=10, null=True)),
                ('desc_turno', models.CharField(blank=True, db_column='DESC_turno', max_length=60, null=True)),
                ('unid_negoc', models.CharField(blank=True, max_length=6, null=True)),
                ('des_unid_negoc', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_pais', models.CharField(blank=True, max_length=6, null=True)),
                ('localidade', models.CharField(blank=True, max_length=80, null=True)),
                ('des_localidade', models.CharField(blank=True, max_length=80, null=True)),
                ('mao_de_obra', models.CharField(blank=True, max_length=6, null=True)),
                ('desc_mao_de_obra', models.CharField(blank=True, db_column='DESC_mao_de_obra', max_length=40, null=True)),
                ('desc_categ_sal', models.CharField(blank=True, max_length=6, null=True)),
                ('cod_cargo', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_nivel', models.CharField(blank=True, max_length=10, null=True)),
                ('des_nivel', models.CharField(blank=True, max_length=72, null=True)),
                ('fpas', models.CharField(blank=True, max_length=10, null=True)),
                ('desc_tomador', models.CharField(blank=True, db_column='DESC_tomador', max_length=50, null=True)),
                ('sat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
                ('hora', models.TimeField(blank=True, db_column='HORA', null=True)),
                ('salario', models.DecimalField(blank=True, db_column='Salario', decimal_places=2, max_digits=10, null=True)),
                ('insalubridade', models.CharField(blank=True, max_length=10, null=True)),
                ('periculosidade', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo', models.CharField(blank=True, db_column='SEXO', max_length=1, null=True)),
                ('desc_demissao', models.CharField(blank=True, db_column='DESC_DEMISSAO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'bi_funcionarios_combio',
                'managed': False,
            },
        ),
    ]
