# Generated by Django 5.0.2 on 2025-04-11 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnificacaoSPED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo_principal', models.CharField(max_length=255)),
                ('nomes_arquivos_secundarios', models.TextField(help_text='Separados por vírgula')),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='sped_unificador/resultados/')),
                ('data_processo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
