# Generated by Django 5.0.2 on 2025-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MondayToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('monday_key', models.CharField(max_length=400)),
                ('monday_board', models.BigIntegerField()),
            ],
            options={
                'db_table': 'monday_tokens',
            },
        ),
    ]
