# Generated by Django 5.0.2 on 2025-08-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinggyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('token', models.CharField(help_text='Use o token exibido no dashboard do Pinggy', max_length=120)),
                ('subdominio', models.CharField(blank=True, help_text='Subdomínio persistente (Pro)', max_length=120, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('auto_start', models.BooleanField(default=False, help_text='Subir túnel automaticamente (via Celery/management task)')),
                ('observacoes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Token Pinggy',
                'verbose_name_plural': 'Tokens Pinggy',
            },
        ),
        migrations.CreateModel(
            name='PinggyRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('http', 'HTTP/HTTPS'), ('tcp', 'TCP'), ('udp', 'UDP'), ('tls', 'TLS')], default='http', max_length=10)),
                ('host_local', models.CharField(default='localhost', max_length=120)),
                ('porta_local', models.PositiveIntegerField()),
                ('sni_local', models.CharField(blank=True, help_text='Para HTTPS local opcionalmente informe SNI', max_length=120, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('url_publica', models.URLField(blank=True, null=True)),
                ('porta_publica', models.PositiveIntegerField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('ultimo_check', models.DateTimeField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='integracoes.pinggytoken')),
            ],
            options={
                'verbose_name': 'Redirecionamento',
                'verbose_name_plural': 'Redirecionamentos',
            },
        ),
    ]
