# Generated by Django 5.0.2 on 2024-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_servidorfluig'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidorfluig',
            name='url',
            field=models.CharField(default='url', max_length=255),
            preserve_default=False,
        ),
    ]
