# Generated by Django 5.0.2 on 2024-11-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_imagem', models.ImageField(blank=True, null=True, upload_to='papeldeparede/')),
                ('nome_arquivo', models.CharField(blank=True, max_length=100)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('padrao_papel_parede', models.BooleanField(default=False)),
                ('padrao_bloqueio_tela', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('usuario_alteracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_alteracao', to=settings.AUTH_USER_MODEL)),
                ('usuario_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_inclusao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
