# Generated by Django 5.0.2 on 2024-11-17 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofre', '0002_vault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanager',
            name='usuario_criacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='password_creations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordmanager',
            name='vault',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='passwords', to='cofre.vault', verbose_name='Cofre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordmanager',
            name='visualizacao',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('PERSONAL', 'Pessoal')], default='TODOS', max_length=10, verbose_name='Visualização'),
        ),
    ]
