# Generated by Django 5.0.2 on 2024-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FluigDatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=255)),
                ('database_version', models.CharField(max_length=255)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fluig_database_info',
            },
        ),
        migrations.CreateModel(
            name='FluigDatabaseSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fluig_database_size',
            },
        ),
        migrations.CreateModel(
            name='FluigDetailedMemoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.BigIntegerField()),
                ('used', models.BigIntegerField()),
                ('committed', models.BigIntegerField()),
                ('max', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fluig_detailed_memory_usage',
            },
        ),
        migrations.CreateModel(
            name='FluigOperationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_memory_size', models.BigIntegerField()),
                ('server_memory_free', models.BigIntegerField()),
                ('server_hd_space', models.CharField(max_length=255)),
                ('server_hd_space_free', models.CharField(max_length=255)),
                ('server_core_system', models.IntegerField()),
                ('server_arch_system', models.CharField(max_length=255)),
                ('server_temp_size', models.BigIntegerField()),
                ('server_log_size', models.BigIntegerField()),
                ('heap_max_size', models.BigIntegerField()),
                ('heap_size', models.BigIntegerField()),
                ('system_uptime', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fluig_operation_system',
            },
        ),
        migrations.CreateModel(
            name='FluigRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField()),
                ('uptime', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fluig_runtime',
            },
        ),
    ]
