# Generated by Django 5.0.2 on 2024-03-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FluigDetailedMemoryUsage',
        ),
    ]
