# Generated by Django 5.0.2 on 2024-03-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_servidorfluig_url'),
        ('api_v1', '0002_delete_fluigdetailedmemoryusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluigdatabaseinfo',
            name='servidor_fluig',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='administration.servidorfluig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluigdatabasesize',
            name='servidor_fluig',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='administration.servidorfluig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluigoperationsystem',
            name='servidor_fluig',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='administration.servidorfluig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluigruntime',
            name='servidor_fluig',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='administration.servidorfluig'),
            preserve_default=False,
        ),
    ]
