# Generated by Django 5.0.2 on 2024-04-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_arquivo_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo_ativo',
            name='arquivo_original',
            field=models.FileField(upload_to='uploads/ativos'),
        ),
    ]
