# Generated by Django 5.0.2 on 2024-04-24 19:29

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_arquivo_ativo_arquivo_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo_ativo',
            name='arquivo_final',
            field=models.FileField(upload_to=utils.models.pasta_upload_ativo),
        ),
        migrations.AlterField(
            model_name='arquivo_ativo',
            name='arquivo_original',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
