# Generated by Django 5.0.2 on 2024-04-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_arquivo_ativo_arquivo_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo_ativo',
            name='arquivo_original',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
