# Generated by Django 5.0.2 on 2024-04-25 17:17

import django.db.models.deletion
import django.utils.timezone
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_arquivo_ativo_arquivo_original'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arquivo_ativo',
            new_name='ArquivoAtivo',
        ),
        migrations.CreateModel(
            name='AtivoValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_original', models.FileField(upload_to='uploads/')),
                ('data_processamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('arquivo_final', models.FileField(upload_to=utils.models.pasta_upload_ativo_valores)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
