# Generated by Django 5.0.2 on 2024-02-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensmenu',
            name='codigo',
            field=models.CharField(max_length=40),
        ),
    ]
