# Generated by Django 5.0.2 on 2024-03-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_itensmenu_codigo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupomenu',
            table='grupomenu',
        ),
        migrations.AlterModelTable(
            name='itensmenu',
            table='itensmenu',
        ),
    ]
