# Generated by Django 5.0.2 on 2024-03-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_grupomenu_table_alter_itensmenu_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupomenu',
            old_name='NomeGrupo',
            new_name='nomegrupo',
        ),
        migrations.RenameField(
            model_name='itensmenu',
            old_name='Item',
            new_name='item',
        ),
    ]
