# Generated by Django 5.0.2 on 2024-03-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_nomegrupo_grupomenu_nomegrupo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupomenu',
            old_name='nomegrupo',
            new_name='NomeGrupo',
        ),
    ]
