# Generated by Django 5.0.2 on 2024-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_nomegrupo_grupomenu_nomegrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomenu',
            name='order',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='itensmenu',
            name='order',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
