# Generated by Django 5.0.2 on 2024-07-19 18:09

import django.db.models.deletion
import django.utils.timezone
import novosProjetos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosProjetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('data_entrega', models.DateField(default=django.utils.timezone.now)),
                ('horas_utilizadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao_solucao', models.TextField()),
                ('anexo_escopo', models.FileField(upload_to=novosProjetos.models.upload_to)),
                ('anexo_documentacao', models.FileField(upload_to=novosProjetos.models.upload_to)),
                ('anexo_fontes', models.FileField(upload_to=novosProjetos.models.upload_to)),
                ('consultoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novosProjetos.consultoria')),
                ('sistemas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novosProjetos.sistemas')),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
    ]
