# Generated by Django 5.0.2 on 2024-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosProjetos', '0004_alter_projeto_anexo_documentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoria',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
