# Generated by Django 5.0.2 on 2024-11-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosProjetos', '0005_consultoria_valor_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoria',
            name='horas_restantes_pagas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consultoria',
            name='total_horas_projetos_pagos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='utilizou_horas_pagas',
            field=models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')], default=2),
        ),
    ]
